---
- name: Prepare localhost (only on CI)
  hosts: localhost
  connection: local

  tasks:
    - name: Install OS packages
      when: lookup('ansible.builtin.env', '__is_ci') | d('false', true) | bool
      ansible.builtin.package:
        name: unzip
      become: true

    - name: Install netaddr dependency on controlling host
      when: lookup('ansible.builtin.env', '__is_ci') | d('false', true) | bool
      ansible.builtin.pip:
        name: netaddr
      become: false

- name: Prepare all hosts
  hosts: all

  pre_tasks:
    # - name: Install kmod
    #   when: patroni_watchdog_mode | d('off') in ('automatic', 'required')
    #   ansible.builtin.package:
    #     name: kmod
    #   timeout: 120

    # - name: Install dig
    #   ansible.builtin.package:
    #     name: "{{ ansible_os_family | lower == 'redhat' | ternary('bind-utils', 'dnsutils') }}"
    - name: Attempt to disable systemd-resolved
      failed_when: false
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
        # daemon_reload: true

    - name: Make /etc/resolv.conf be a regular file
      block:
        - name: Copy original resolvconf
          ansible.builtin.copy:
            src: /etc/resolv.conf
            dest: /etc/resolv.conf.pre_molecule_run
            mode: preserve
            remote_src: true

        - name: Ensure resolvconf is unmounted
          ansible.posix.mount:
            path: /etc/resolv.conf
            state: unmounted
          register: resolvconf_unmount_res

        - name: Restore original resolvconf
          when: resolvconf_unmount_res is changed
          ansible.builtin.copy:
            src: /etc/resolv.conf.pre_molecule_run
            dest: /etc/resolv.conf
            remote_src: true
            mode: preserve
          tags: skip_ansible_lint
