---
- name: Create /etc/udev/rules.d/
  ansible.builtin.file:
    path: /etc/udev/rules.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create udev rule for watchdog
  ansible.builtin.copy:
    content: 'KERNEL=="{{ patroni_watchdog_device | basename }}", OWNER="{{ patroni_system_user }}", GROUP="{{ patroni_system_group }}", MODE="0600"'
    dest: /etc/udev/rules.d/60-watchdog.rules
    owner: root
    group: root
    mode: "0644"

- name: Install watchdog
  ansible.builtin.package:
    name: watchdog
    update_cache: true
  environment: "{{ _patroni_pkg_proxy_env }}"

- name: Ensure /sbin/modprobe exists
  changed_when: false
  ansible.builtin.command:
    cmd: /sbin/modprobe --help

- name: Make kernel watchdog device available for patroni
  ansible.builtin.template:
    src: etc/systemd/system/patroni-watchdog.service.j2
    dest: /etc/systemd/system/patroni-watchdog.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart patroni-watchdog

# Dirty hack. See https://bugs.launchpad.net/ubuntu/+source/watchdog/+bug/1448924
# - name: Enable watchdog daemon to start on boot
#   when: ansible_distribution in ('Ubuntu', 'Debian') and ansible_distribution_release in ('xenial', 'jessie')
#   ansible.builtin.file:
#     src: /lib/systemd/system/watchdog.service
#     dest: /etc/systemd/system/multi-user.target.wants/watchdog.service
#     state: link

- name: Config watchdog
  ansible.builtin.lineinfile:
    path: /etc/watchdog.conf
    regexp: '^#watchdog-device'
    line: "watchdog-device = {{ patroni_watchdog_device }}"
  notify:
    - Restart patroni-watchdog
